Repository 0Upjh80d/agents, pull requests merged in 2025-04, with the labels that each got.

#54 docs: add reviewer's step-by-step guide
  .github/workflows/lint-markdown.yml
  CONTRIBUTING.md
  docs/CONTRIBUTORS_STEP_BY_STEP.md
  docs/REVIEWERS_STEP_BY_STEP.md
  event.json
Labels: documentation

#59 feat: allow nearest clinic to return both gp and polyclinic
  app/backend/app/routers/clinic.py
Labels: enhancement

#58 feat: sort available booking slots by distance from user
  app/backend/app/routers/booking.py
  pyproject.toml
  uv.lock
Labels: enhancement

#60 fix: remove html from link checker
  .github/workflows/validate-markdown.yml
  docs/API_ENDPOINTS.md
Labels: bug

#69 test: add test cases for `bookings/`, `clinics/` endpoints; update `/bookings/{id}` and `/vaccines/recommendations` endpoints
  app/backend/app/routers/booking.py
  app/backend/app/routers/clinic.py
  app/backend/app/routers/vaccine.py
  app/backend/app/schemas/vaccine.py
  app/backend/app/tests/conftest.py
  app/backend/app/tests/test_booking.py
  app/backend/app/tests/test_clinic.py
  app/backend/app/tests/test_vaccine.py
  data/data.sql
  docs/API_ENDPOINTS.md
Labels: bug, enhancement

#76 feat: frontend integration with dummy backend & display URLs in iFrame
  app/backend/app/routers/dummy_orchestrator.py
  app/frontend/src/app/components/vaccine-index/vaccine-index.component.html
  app/frontend/src/app/components/vaccine-index/vaccine-index.component.ts
  app/frontend/src/app/services/endpoint.service.ts
Labels: enhancement

#72 fix: modify subjectPattern for validating PR titles
  .github/workflows/run-tests.yml
  .github/workflows/validate-pr.yml
  app/backend/app/main.py
  scripts/functions.sh
  scripts/start.ps1
  scripts/start.sh
Labels: bug

#79 fix: remove duplicate case 'vaccine_list' in handleUserInput function
  app/frontend/src/app/components/vaccine-index/vaccine-index.component.ts
Labels: bug

#78 refactor: moved functions used in start.ps1 to separate script
  .github/workflows/run-checks.yml
  scripts/functions.ps1
  scripts/start.ps1
Labels: enhancement

#84 feat: new login ui to replace the previous singpass-like ui
  app/frontend/src/app/components/vaccine-index/vaccine-index.component.html
  app/frontend/src/app/components/vaccine-index/vaccine-index.component.ts
Labels: enhancement
