Repository 0Upjh80d/agents, pull requests merged in 2025-03, with the labels that each got.

#3 docs: minor reformat and update docs; update changelog
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/DEVELOPMENT.md
  docs/PROJECT_STRUCTURE.md
Labels: documentation

#6 fix: fix GHA skip internally if no files changed to avoid stuck PR (#5)
  .github/workflows/lint-markdown.yml
Labels: bug

#10 Add Scripts to Assign RBAC Roles After Post Provision Phase
  CHANGELOG.md
  docs/PROJECT_STRUCTURE.md
  infra/main.bicep
  scripts/postprovision.sh
  scripts/rolesgroup.ps1
  scripts/rolesgroup.sh
  scripts/test.sh
Labels: documentation, enhancement

#8 feat: added startup scripts, simple chat endpoint, readme
  Makefile
  app/backend/app/README.md
  app/backend/app/main.py
  app/backend/app/routers/chat.py
  app/backend/app/schema/chat.py
  docs/DEVELOPMENT.md
  pyproject.toml
  scripts/start.ps1
  scripts/start.sh
  uv.lock
Labels: enhancement

#18 chore: add additional regex check for release branches
  .githooks/commit-msg
  .githooks/pre-push
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/PROJECT_STRUCTURE.md
  pyproject.toml
Labels: enhancement

#19 chore(release): update documentation, GHA workflows and scripts; updates and changes log into CHANGELOG
  .github/workflows/lint-markdown.yml
  .github/workflows/run-checks.yml
  .github/workflows/validate-pr.yml
  CHANGELOG.md
  data/vaccination_db.sqlite.dvc
  docs/DEVELOPMENT.md
  docs/PROJECT_STRUCTURE.md
  infra/main.bicep
  notebooks/query_database.ipynb
  scripts/postprovision.sh
  scripts/rolesgroup.ps1
  scripts/rolesgroup.sh
  scripts/test.sh
Labels: release, cherry-picked

#16 feat: change link checker to lychee
  .github/workflows/validate-markdown.yml
  .lycheeignore
Labels: enhancement

#21 feat: update README and Project structure documentation
  CONTRIBUTING.md
  app/backend/app/README.md
  docs/ALTERNATIVE_PYTHON_PACKAGE_MANAGERS.md
  docs/DEVELOPMENT.md
  docs/PROJECT_STRUCTURE.md
Labels: documentation

#27 chore(release): simple chat endpoint, integrated ORM framework, created endpoints, schemas and models
  .github/.linkspector.yml
  .github/workflows/validate-markdown.yml
  .lycheeignore
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  app/backend/app/README.md
  app/backend/app/main.py
  app/backend/app/models/database.py
  app/backend/app/models/models.py
  app/backend/app/routers/booking.py
  app/backend/app/routers/chat.py
  app/backend/app/routers/record.py
  app/backend/app/routers/stock.py
  app/backend/app/routers/user.py
  app/backend/app/schemas/__init__.py
  app/backend/app/schemas/base.py
  app/backend/app/schemas/booking.py
  app/backend/app/schemas/chat.py
  app/backend/app/schemas/polyclinic.py
  app/backend/app/schemas/record.py
  app/backend/app/schemas/stock.py
  app/backend/app/schemas/user.py
  app/backend/app/schemas/vaccine.py
  data/schema.sql
  data/vaccination_db.sqlite.dvc
  docs/ALTERNATIVE_PYTHON_PACKAGE_MANAGERS.md
  docs/DEVELOPMENT.md
  docs/PROJECT_STRUCTURE.md
  pyproject.toml
  scripts/start.ps1
  scripts/start.sh
  scripts/test.ps1
  uv.lock
Labels: release, cherry-picked

#25 feat: updated dummy database with improved schema and more rows
  data/vaccination_db.sqlite.dvc
  notebooks/query_database.ipynb
Labels: enhancement

#30 feat: update dummy database with improved schema and more data rows
  data/schema.sql
  data/vaccination_db.sqlite.dvc
  notebooks/genarate_database.ipynb
  notebooks/query_database.ipynb
Labels: enhancement

#32 feat: implement OAuth2 authentication flow in FastAPI
  app/backend/app/.env.sample
  app/backend/app/auth/oauth2.py
  app/backend/app/auth/password.py
  app/backend/app/core/config.py
  app/backend/app/main.py
  app/backend/app/models/models.py
  app/backend/app/routers/authentication.py
  app/backend/app/routers/booking.py
  app/backend/app/routers/record.py
  app/backend/app/routers/stock.py
  app/backend/app/routers/user.py
  app/backend/app/schemas/base.py
  app/backend/app/schemas/booking.py
  app/backend/app/schemas/oauth2.py
  app/backend/app/schemas/user.py
  pyproject.toml
  uv.lock
Labels: enhancement

#34 refactor: major code refactor to account for data schema changes and updates
  .dvc/config
  app/backend/app/auth/oauth2.py
  app/backend/app/main.py
  app/backend/app/models/models.py
  app/backend/app/routers/authentication.py
  app/backend/app/routers/booking.py
  app/backend/app/routers/record.py
  app/backend/app/routers/stock.py
  app/backend/app/routers/user.py
  app/backend/app/routers/vaccine.py
  app/backend/app/schemas/address.py
  app/backend/app/schemas/base.py
  app/backend/app/schemas/booking.py
  app/backend/app/schemas/clinic.py
  app/backend/app/schemas/oauth2.py
  app/backend/app/schemas/polyclinic.py
  app/backend/app/schemas/record.py
  app/backend/app/schemas/stock.py
  app/backend/app/schemas/user.py
  app/backend/app/schemas/vaccine.py
  data/.gitignore
  data/get_instituitions_response.json.dvc
  data/schema.sql
  data/vaccination_db.sqlite.dvc
  notebooks/genarate_database.ipynb
  notebooks/query_database.ipynb
  postman/Agents.postman_collection.json
  postman/DEV-Agents.postman_environment.json
  scripts/get_data.ps1
  scripts/get_data.sh
  scripts/setup_dvc.ps1
  scripts/setup_dvc.sh
Labels: enhancement

#35 feat: created reschedule endpoint; refactor: ensure unique column values, removed user dependency injection, minor update to endpoints
  app/backend/app/models/models.py
  app/backend/app/routers/booking.py
  app/backend/app/routers/record.py
  app/backend/app/schemas/booking.py
Labels: bug, enhancement

#38 docs: added documentation to backend, guides to current API endpoints, database models and Postman API testing
  CHANGELOG.md
  README.md
  app/backend/app/README.md
  docs/API_ENDPOINTS.md
  docs/DATABASE_MODELS.md
  docs/DATA_MANAGEMENT.md
  docs/POSTMAN_TESTING.md
  media/access-token.png
  media/collection.png
  media/environment.png
  media/erd.png
  media/exporting-collections-environments.png
  media/import-collection.png
  media/postman-environment-variables.png
  media/redoc.png
  media/schemas.png
  media/setting-token.png
  media/start-server.png
  media/swagger.png
Labels: documentation

#40 feat: add nearest polyclinic/GP
  app/backend/app/main.py
  app/backend/app/routers/clinic.py
  app/backend/app/schemas/clinic.py
  app/backend/app/schemas/user.py
Labels: enhancement

#44 docs: update API endpoint documentation for reschedule vaccination booking
  docs/API_ENDPOINTS.md
Labels: documentation

#46 feat: add optional datetime args to filter for available bookings
  app/backend/app/routers/booking.py
Labels: enhancement

#47 chore(release): implemented OAuth2, data schema changes, new endpoints, documentation updates, minor endpoint updates
  .dvc/config
  CHANGELOG.md
  README.md
  app/backend/app/.env.sample
  app/backend/app/README.md
  app/backend/app/auth/oauth2.py
  app/backend/app/auth/password.py
  app/backend/app/core/config.py
  app/backend/app/main.py
  app/backend/app/models/models.py
  app/backend/app/routers/authentication.py
  app/backend/app/routers/booking.py
  app/backend/app/routers/clinic.py
  app/backend/app/routers/record.py
  app/backend/app/routers/stock.py
  app/backend/app/routers/user.py
  app/backend/app/routers/vaccine.py
  app/backend/app/schemas/address.py
  app/backend/app/schemas/base.py
  app/backend/app/schemas/booking.py
  app/backend/app/schemas/clinic.py
  app/backend/app/schemas/oauth2.py
  app/backend/app/schemas/polyclinic.py
  app/backend/app/schemas/record.py
  app/backend/app/schemas/stock.py
  app/backend/app/schemas/user.py
  app/backend/app/schemas/vaccine.py
  data/.gitignore
  data/get_instituitions_response.json.dvc
  data/schema.sql
  data/vaccination_db.sqlite.dvc
  docs/API_ENDPOINTS.md
  docs/DATABASE_MODELS.md
  docs/DATA_MANAGEMENT.md
  docs/POSTMAN_TESTING.md
  media/access-token.png
  media/collection.png
  media/environment.png
  media/erd.png
  media/exporting-collections-environments.png
  media/import-collection.png
  media/postman-environment-variables.png
  media/redoc.png
  media/schemas.png
  media/setting-token.png
  media/start-server.png
  media/swagger.png
  notebooks/genarate_database.ipynb
  notebooks/query_database.ipynb
  postman/Agents.postman_collection.json
  postman/DEV-Agents.postman_environment.json
  pyproject.toml
  scripts/get_data.ps1
  scripts/get_data.sh
  scripts/setup_dvc.ps1
  scripts/setup_dvc.sh
  uv.lock
Labels: release, cherry-picked
